namespace: default

frontend:
  replicaCount: 1

catalogue:
  replicaCount: 1

carts:
  replicaCount: 1

frontend:
  image:
    repository: 440946411147.dkr.ecr.us-west-2.amazonaws.com/platform-demo/frontend
    tag: latest

payment:
  image:
    repository: 440946411147.dkr.ecr.us-west-2.amazonaws.com/platform-demo/payment
    tag: latest
