apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment

  template:
    metadata:
      labels:
        app: payment

    spec:
      containers:
      - name: payment

        image: "{{ .Values.payment.image.repository }}:{{ .Values.payment.image.tag }}"

        ports:
        - containerPort: 8080

        env:
        - name: OTEL_SERVICE_NAME
          value: payment-service

        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER 
          value: otlp
       