apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: platform-demo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/srkaluva/platform_engineering.git

    targetRevision: feature-baseline

    path: helm/platform-demo

  destination:
    server: https://kubernetes.default.svc

    namespace: default

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
